source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

target 'ReactiveCocoaDemo' do
    pod 'AFNetworking'
    pod 'Masonry'
    pod 'FMDB'
    pod 'SDWebImage'
    pod 'ReactiveObjC'
    pod 'KVOController'
    pod 'MJExtension'
    pod 'MJRefresh'
    pod 'MBProgressHUD'
    pod 'Colours'

#    pod 'YYKit'
    pod 'YYCategories'
    pod 'YYText'
    pod 'YYModel'
    pod 'YYImage'
    pod 'YYImage/WebP'
    pod 'YYCache'
    pod 'YYWebImage'
    pod 'YYKeyboardManager'
    pod 'YYDispatchQueuePool'
    pod 'YYAsyncLayer'

    target 'ReactiveCocoaDemoTests' do
    end

    target 'ReactiveCocoaDemoUITests' do
    end

end


